import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored === 'en' || stored === 'es') ? stored : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.feed": "Devil's Diary",
    "nav.reels": "Sinners Synagogue",
    "nav.friends": "Allies",
    "nav.covens": "Covens",
    "nav.chat": "Infernal Chat",
    "nav.ouija": "Ouija Chamber",
    "nav.tarot": "Tarot Reading",
    "nav.rune": "Rune Casting",
    "nav.solomon": "Solomon's Chamber",
    "nav.calendar": "Ritual Calendar",

    // Solomon's Chamber
    "solomon.title": "Solomon's Chamber",
    "solomon.subtitle": "Select your demonic sigil from the 72 spirits of the Ars Goetia",
    "solomon.primeLevel": "Prime Level",
    "solomon.goetiaTab": "Goetia Sigils",
    "solomon.lockedTab": "Locked Content",
    "solomon.filterRank": "Rank",
    "solomon.filterDomain": "Domain",
    "solomon.all": "All",
    "solomon.spiritNumber": "Spirit #",
    "solomon.ofGoetia": "of the Ars Goetia",
    "solomon.unlocked": "Unlocked",
    "solomon.level": "Level",
    "solomon.lockedContent": "Locked content",
    "solomon.unlockContent": "Unlock Content",
    "solomon.viewContent": "View Content",
    "solomon.toast.bound": "bound to your essence",
    "solomon.toast.failed": "Failed to bind sigil",
    "solomon.toast.unlockSuccess": "Content Unlocked!",
    "solomon.toast.unlockDesc": "Knowledge is power in the darkness",
    "solomon.toast.unlockFailed": "Failed to unlock content",
    "solomon.toast.requiresLevel": "Requires Prime Level",
    "solomon.toast.currentLevel": "Your current level",

    // Goetia Demon Descriptions
    "demon.1": "Commands 66 legions. Grants invisibility and wisdom.",
    "demon.2": "Commands 31 legions. Teaches languages and causes earthquakes.",
    "demon.3": "Commands 26 legions. Reveals hidden things and the future.",
    "demon.4": "Commands 30 legions. Teaches liberal sciences and necromancy.",
    "demon.5": "Commands 36 legions. Reveals truth and heals diseases.",
    "demon.6": "Commands 10 legions. Leads to hidden treasures and familiars.",
    "demon.7": "Commands 40 legions. Reveals the past and future, reconciles.",
    "demon.8": "Commands 30 legions. Speaks with animals and finds treasure.",
    "demon.9": "Commands 200 legions. Teaches all arts, sciences, and secrets.",
    "demon.10": "Commands 50 legions. Teaches philosophy and healing herbs.",
    "demon.11": "Commands 40 legions. Reveals answers and reconciles friendships.",
    "demon.12": "Commands 60 legions. Inflames love and reveals secrets.",
    "demon.13": "Commands 85 legions. Causes all love and commands respect.",
    "demon.14": "Commands 30 legions. Causes battles and wounds.",
    "demon.15": "Commands 60 legions. Reveals hidden things and war secrets.",
    "demon.16": "Commands 26 legions. Causes love and makes barren.",
    "demon.17": "Commands 60 legions. Reveals past, present, and future.",
    "demon.18": "Commands 30 legions. Knows virtues of herbs and precious stones.",
    "demon.19": "Commands 30 legions. Causes love between man and woman.",
    "demon.20": "Commands 22 legions. Knows all hidden things and treasures.",
    "demon.21": "Commands 30 legions. Teaches astronomy and liberal arts.",
    "demon.22": "Commands 36 legions. Knows past, present, and future.",
    "demon.23": "Commands 26 legions. Sets cities ablaze and makes witty.",
    "demon.24": "Commands 19 legions. Teaches arts and sciences eloquently.",
    "demon.25": "Commands 36 legions. Teaches all arts and causes bloodshed.",
    "demon.26": "Commands 30 legions. Grants riches, wisdom, and eloquence.",
    "demon.27": "Commands 19 legions. Teaches rhetoric and languages.",
    "demon.28": "Commands 26 legions. Turns metals to gold and reveals truth.",
    "demon.29": "Commands 40 legions. Answers questions about the past.",
    "demon.30": "Commands 29 legions. Teaches rhetoric and makes loved.",
    "demon.31": "Commands 29 legions. Teaches logic and ethics.",
    "demon.32": "Commands 72 legions. Teaches arithmetic and makes invisible.",
    "demon.33": "Commands 66 legions. Makes insensible and causes love.",
    "demon.34": "Commands 26 legions. Causes love and raises storms.",
    "demon.35": "Commands 30 legions. Answers truly and hopes to return.",
    "demon.36": "Commands 26 legions. Teaches astronomy and herbs.",
    "demon.37": "Commands 20 legions. Teaches sciences and poetry.",
    "demon.38": "Commands 26 legions. Builds towers and supplies weapons.",
    "demon.39": "Commands 40 legions. Builds houses and destroys enemies.",
    "demon.40": "Commands 30 legions. Steals treasures and destroys cities.",
    "demon.41": "Commands 30 legions. Controls winds and drowns men.",
    "demon.42": "Commands 29 legions. Guides waters and causes death.",
    "demon.43": "Commands 50 legions. Builds castles and afflicts wounds.",
    "demon.44": "Commands 30 legions. Steals and discovers hidden things.",
    "demon.45": "Commands 36 legions. Reveals witches and builds towers.",
    "demon.46": "Commands 6 legions. Teaches astrology and geometry.",
    "demon.47": "Commands 37 legions. Procures love and reveals past.",
    "demon.48": "Commands 33 legions. Transmutes metals and gives wisdom.",
    "demon.49": "Commands 48 legions. Teaches geometry and warms waters.",
    "demon.50": "Commands 20 legions. Teaches philosophy and divination.",
    "demon.51": "Commands 40 legions. Gives invisibility and wit.",
    "demon.52": "Commands 36 legions. Teaches astronomy and liberal arts.",
    "demon.53": "Commands 30 legions. Gives understanding of animals.",
    "demon.54": "Commands 30 legions. Teaches philosophy and constrains souls.",
    "demon.55": "Commands 20 legions. Reveals truth and protects.",
    "demon.56": "Commands 26 legions. Tells of treasures and procures love.",
    "demon.57": "Commands 3 legions. Transforms and makes insane.",
    "demon.58": "Commands 36 legions. Teaches astrology and liberal arts.",
    "demon.59": "Commands 30 legions. Teaches astrology and transforms.",
    "demon.60": "Commands 36 legions. Teaches crafts and philosophy.",
    "demon.61": "Commands 33 legions. Transmutes and makes witty.",
    "demon.62": "Commands 38 legions. Reveals serpents and treasures.",
    "demon.63": "Commands 30 legions. Sows discord and slays.",
    "demon.64": "Commands 36 legions. Reveals past and destroys enemies.",
    "demon.65": "Commands 30 legions. Teaches geometry and astronomy.",
    "demon.66": "Commands 20 legions. Teaches grammar and reveals treasure.",
    "demon.67": "Commands 29 legions. Gives musical instruments.",
    "demon.68": "Commands 80 legions. Distributes titles and gives familiars.",
    "demon.69": "Commands 30 legions. Knows virtues of birds and stones.",
    "demon.70": "Commands 26 legions. Travels quickly and reveals thieves.",
    "demon.71": "Commands 36 legions. Knows thoughts and changes them.",
    "demon.72": "Commands 36 legions. Reveals thieves and punishes.",

    "nav.store": "Prime Store",
    "nav.profile": "My Castle",
    "nav.settings": "Settings",
    "nav.viewCastle": "View Castle",
    "nav.premiumServices": "Premium Services",

    // Header
    "header.search": "Search the darkness...",
    "header.notifications": "Notifications",
    "header.castle": "My Castle",

    // Tarot Reading
    "tarot.title": "🔮 Tarot Reading Chamber",
    "tarot.previousReadings": "Previous readings",
    "tarot.accessRequired": "Access to the Tarot Chamber requires a reading key or invite token.",
    "tarot.enterToken": "Enter Your Token",
    "tarot.tokenPlaceholder": "XXXX-XXXX-XXXX",
    "tarot.validateToken": "Validate Token",
    "tarot.purchaseKey": "Or purchase a reading key from the store",
    "tarot.spreadType": "Spread Type",
    "tarot.spiritTone": "Spirit Tone",
    "tarot.beginReading": "Begin Reading",
    "tarot.interpretation": "Interpretation",
    "tarot.exportTranscript": "Export Transcript",
    "tarot.newReading": "New Reading",
    "tarot.drawingCards": "Drawing cards from the cosmic deck...",
    "tarot.reversed": "Reversed",
    
    // Spread Types
    "tarot.spread.1card": "Single Card - Quick Insight",
    "tarot.spread.3card": "Three Card - Past, Present, Future",
    "tarot.spread.celtic": "Celtic Cross - Deep Dive",
    
    // Spirit Tones
    "tarot.tone.poetic": "Poetic - Mystical & Metaphorical",
    "tarot.tone.factual": "Factual - Direct & Practical",
    "tarot.tone.chaotic": "Chaotic - Unpredictable & Wild",
    "tarot.tone.silent": "Silent - Minimal Words, Deep Meaning",

    // Rune Casting
    "rune.title": "⚔️ Rune Casting Chamber",
    "rune.previousCastings": "Previous castings",
    "rune.accessRequired": "Access to the Rune Chamber requires a casting key or invite token.",
    "rune.enterToken": "Enter Your Token",
    "rune.tokenPlaceholder": "XXXX-XXXX-XXXX",
    "rune.validateToken": "Validate Token",
    "rune.purchaseKey": "Or purchase a casting key from the store",
    "rune.spreadType": "Spread Type",
    "rune.spiritTone": "Spirit Tone",
    "rune.beginCasting": "Begin Casting",
    "rune.interpretation": "Interpretation",
    "rune.exportTranscript": "Export Transcript",
    "rune.newCasting": "New Casting",
    "rune.castingRunes": "Casting runes from the ancient set...",
    "rune.reversed": "Reversed",
    "rune.spread.1rune": "Single Rune - Quick Insight",
    "rune.spread.3rune": "Three Rune - Past, Present, Future",
    "rune.spread.9rune": "Nine Rune Grid - Full Spiritual Map",
    "rune.tone.poetic": "Poetic - Mystical & Metaphorical",
    "rune.tone.factual": "Factual - Direct & Practical",
    "rune.tone.chaotic": "Chaotic - Unpredictable & Wild",
    "rune.tone.silent": "Silent - Minimal Words, Deep Meaning",
    "rune.error.invalidToken": "Invalid or already used token",
    "rune.error.startFailed": "Failed to start casting session",
    "rune.error.castFailed": "Failed to cast runes",
    "rune.error.interpretFailed": "Failed to generate interpretation",
    "rune.success.accessGranted": "Access granted! Your token has been activated.",
    "rune.success.exported": "Transcript exported",

    // Ouija Chamber
    "ouija.title": "Infernal Ouija Chamber",
    "ouija.subtitle": "Create a séance room and invite up to 5 friends. Each session allows 6 questions before the spirits depart.",
    "ouija.createRoom": "Create Room",
    "ouija.summonSpirit": "Summon Spirit",
    "ouija.tokenCode": "Token Code",
    "ouija.adminOptional": "(Admin: Optional)",
    "ouija.enterToken": "Enter your token code",
    "ouija.creating": "Creating...",
    "ouija.createSeance": "Create Séance Room",
    "ouija.purchaseToken": "Purchase Token (Demo)",
    "ouija.tokenInfo": "Tokens are consumable and allow you to host one séance session. Share the invite code with up to 5 participants.",
    "ouija.summonedSpirit": "Summoned Spirit",
    "ouija.questionsRemaining": "Questions Remaining",
    "ouija.currentTurn": "Current Turn",
    "ouija.you": "(You)",
    "ouija.copyInvite": "Copy Invite",
    "ouija.participants": "Participants",
    "ouija.spiritSpeaks": "The spirit speaks through movement...",
    "ouija.watchPlanchette": "Watch the planchette spell the answer",
    "ouija.hoveringOver": "Hovering over:",
    "ouija.askQuestion": "Ask the spirits a question...",
    "ouija.askSpirit": "Ask Spirit",
    "ouija.spiritResponses": "Spirit Responses",
    "ouija.clearLog": "Clear Log",
    "ouija.sessionEnded": "Session Ended",
    "ouija.spiritsDepart": "The spirits have departed after 6 questions.",
    "ouija.questionsAsked": "Questions Asked:",
    "ouija.exitRoom": "Exit Room",
    "ouija.inviteCopied": "Invite Link Copied!",
    "ouija.inviteDesc": "Share this link with up to 5 participants.",
    "ouija.tokenRequired": "Token Required",
    "ouija.tokenRequiredDesc": "Please enter your token code to create a room.",
    "ouija.invalidToken": "Invalid Token",
    "ouija.invalidTokenDesc": "This token doesn't exist or has already been used.",
    "ouija.roomCreated": "Room Created!",
    "ouija.shareInvite": "Share invite code:",
    "ouija.error": "Error",
    "ouija.errorDesc": "An unexpected error occurred.",
    "ouija.tokenPurchased": "Token Purchased!",
    "ouija.yourToken": "Your token code:",
    "ouija.spiritsReached": "The spirits could not be reached.",
    "ouija.letterDetected": "Letter Detected",
    "ouija.spiritHovers": "The spirit hovers over:",
    "ouija.spirits.the_whisperer": "The Whisperer",
    "ouija.spirits.the_archivist": "The Archivist",
    "ouija.spirits.the_trickster": "The Trickster",
    "ouija.spirits.the_watcher": "The Watcher",
    "ouija.spirits.the_whisperer_desc": "Cryptic, poetic replies",
    "ouija.spirits.the_archivist_desc": "Factual, historical responses",
    "ouija.spirits.the_trickster_desc": "Chaotic, misleading answers",
    "ouija.spirits.the_watcher_desc": "Silent, cryptic symbols",

    // Common Actions
    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.delete": "Delete",
    "action.edit": "Edit",
    "action.create": "Create",
    "action.update": "Update",
    "action.close": "Close",
    "action.submit": "Submit",

    // Notifications
    "notification.success": "Success",
    "notification.error": "Error",
    "notification.warning": "Warning",
    "notification.info": "Information",

    // Auth
    "auth.login": "Login",
    "auth.logout": "Logout",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",

    // Profile
    "profile.edit": "Edit Profile",
    "profile.username": "Username",
    "profile.bio": "Bio",
    "profile.location": "Location",
    "profile.dateOfBirth": "Date of Birth",
    "profile.zodiac": "Zodiac Sign",
    "profile.background": "Background",
    "profile.careerFocus": "Career Focus",
    "profile.relationship": "Relationship Status",

    // Video Upload
    "upload.title": "Upload Your Infernal Content",
    "upload.uploadText": "Upload Your Video!",
    "upload.clickOrDrag": "Click to select or drag and drop",
    "upload.maxSize": "Max 50MB",
    "upload.titleLabel": "Title",
    "upload.titlePlaceholder": "The Midnight Ritual...",
    "upload.categoryLabel": "Video Category (7 Deadly Sins)",
    "upload.categoryPlaceholder": "Select a category...",
    "upload.descriptionLabel": "Content Description",
    "upload.descriptionPlaceholder": "Speak the words of power...",
    "upload.tagsLabel": "Add Your Hash Tags#",
    "upload.tagsPlaceholder": "Add tag...",
    "upload.addButton": "Add",
    "upload.unleashButton": "Unleash Video",
    "upload.uploading": "Summoning...",
    "upload.disciples": "Video Disciples",
    "upload.legionUnlocked": "6 Legions Unlocked - 5min videos enabled",
    "upload.toLegion": "more to unlock 6 Legions",
    "upload.maxSize60sec": "Max 60 seconds (need 6,000 disciples for 3-5min)",
    "upload.maxSize5min": "Max 5 minutes - 50MB",
    "upload.error.notVideo": "Please select a video file",
    "upload.error.tooLarge": "Video must be less than 50MB",
    "upload.error.needLegions": "Need 6,000 disciples (6 Legions) to upload videos over 60 seconds",
    "upload.error.max5min": "Maximum video length is 5 minutes (300 seconds)",

    // Reels
    "reels.loadingVideos": "Loading videos...",
    "reels.noVideos": "No videos yet",
    "reels.ritualInterrupted": "Ritual Interrupted",
    "reels.retry": "Retry",
    "reels.anonymous": "Anonymous",
    "reels.loadingMore": "Loading more...",
    "reels.noMoreVideos": "No more videos",
    "reels.alreadyReacted": "Already reacted",

    // Search
    "search.title": "Advanced Search - Devil's Diary",
    "search.placeholder": "Search users, posts, videos, covens...",
    "search.search": "Search",
    "search.searching": "Searching...",
    "search.filterBy": "Filter by",
    "search.all": "All",
    "search.username": "Username",
    "search.location": "Location",
    "search.users": "Users",
    "search.posts": "Posts",
    "search.videos": "Videos",
    "search.covens": "Covens",
    "search.noUsers": "No users found",
    "search.noPosts": "No posts found",
    "search.noVideos": "No videos found",
    "search.noCovens": "No covens found",

    // Occult Library
    "library.title": "📚 Occult Library",
    "library.subtitle": "Ancient Grimoires & Forbidden Knowledge",
    "library.featured": "Featured Tomes",
    "library.collection": "Sacred Collection",
    "library.searchPlaceholder": "Search grimoires...",
    "library.allCategories": "All Categories",
    "library.sortBy": "Sort by",
    "library.newest": "Newest",
    "library.oldest": "Oldest",
    "library.popular": "Most Popular",
    "library.subscribeInfo": "Subscribe for unlimited access to this and all books",
    "library.pricePerMonth": "$29.99/month",
    "library.unlimitedReading": "Unlimited Reading",
    "library.subscribeButton": "Subscribe for Unlimited Access",
    "library.processing": "Processing...",
    "library.read": "Read Now",
    "library.download": "Download",
    "library.preview": "Preview",
    "library.pages": "pages",
    "library.author": "Author",
    "library.published": "Published",
    "library.category": "Category",
    "library.description": "Description",
    "library.chapters": "Chapters",
    "library.reviews": "Reviews",
    "library.rating": "Rating",
    "library.addToLibrary": "Add to Library",
    "library.inLibrary": "In Your Library",
    "library.share": "Share",
    "library.report": "Report",
    "library.relatedBooks": "Related Books",
    "library.noBooks": "No books found",
    "library.loadMore": "Load More",
    "library.categories.rituals": "Rituals & Ceremonies",
    "library.categories.demons": "Demonology",
    "library.categories.spells": "Spells & Incantations",
    "library.categories.history": "Occult History",
    "library.categories.philosophy": "Dark Philosophy",
    "library.categories.divination": "Divination Arts",
    "library.categories.alchemy": "Alchemy",
    "library.categories.astral": "Astral Projection",

    // Settings
    "settings.title": "Settings",
    "settings.profile": "Profile Settings",
    "settings.account": "Account",
    "settings.privacy": "Privacy",
    "settings.notifications": "Notifications",
    "settings.appearance": "Appearance",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.darkMode": "Dark Mode",
    "settings.lightMode": "Light Mode",
    "settings.autoMode": "Auto",
    "settings.emailNotifications": "Email Notifications",
    "settings.pushNotifications": "Push Notifications",
    "settings.soundEffects": "Sound Effects",
    "settings.changePassword": "Change Password",
    "settings.deleteAccount": "Delete Account",
    "settings.privacyPolicy": "Privacy Policy",
    "settings.termsOfService": "Terms of Service",
    "settings.logout": "Logout",
    "settings.saveChanges": "Save Changes",
    "settings.discardChanges": "Discard Changes",

    // Chat
    "chat.title": "Infernal Chat",
    "chat.conversations": "Conversations",
    "chat.newMessage": "New Message",
    "chat.searchMessages": "Search messages...",
    "chat.typePlaceholder": "Type a message...",
    "chat.send": "Send",
    "chat.attach": "Attach",
    "chat.emoji": "Emoji",
    "chat.voiceCall": "Voice Call",
    "chat.videoCall": "Video Call",
    "chat.moreOptions": "More Options",
    "chat.online": "Online",
    "chat.offline": "Offline",
    "chat.typing": "typing...",
    "chat.seen": "Seen",
    "chat.delivered": "Delivered",
    "chat.sent": "Sent",
    "chat.failed": "Failed",
    "chat.deleteMessage": "Delete Message",
    "chat.editMessage": "Edit Message",
    "chat.replyMessage": "Reply",
    "chat.forwardMessage": "Forward",
    "chat.copyMessage": "Copy",
    "chat.noConversations": "No conversations yet",
    "chat.startConversation": "Start a conversation",

    // Feed/Posts
    "feed.title": "Devil's Diary",
    "feed.whatsOnMind": "What's on your dark mind?",
    "feed.createPost": "Create Post",
    "feed.shareThoughts": "Share your thoughts...",
    "feed.addPhoto": "Add Photo",
    "feed.addVideo": "Add Video",
    "feed.addLocation": "Add Location",
    "feed.post": "Post",
    "feed.posting": "Posting...",
    "feed.like": "Like",
    "feed.comment": "Comment",
    "feed.share": "Share",
    "feed.comments": "Comments",
    "feed.writeComment": "Write a comment...",
    "feed.viewAllComments": "View all comments",
    "feed.hideComments": "Hide comments",
    "feed.edited": "Edited",
    "feed.deletePost": "Delete Post",
    "feed.editPost": "Edit Post",
    "feed.reportPost": "Report Post",
    "feed.savePost": "Save Post",
    "feed.unsavePost": "Unsave Post",
    "feed.noPostsYet": "No posts yet",
    "feed.loadingPosts": "Loading posts...",

    // Store
    "store.title": "Prime Store",
    "store.featuredItems": "Featured Items",
    "store.categories": "Categories",
    "store.cart": "Cart",
    "store.checkout": "Checkout",
    "store.addToCart": "Add to Cart",
    "store.buyNow": "Buy Now",
    "store.price": "Price",
    "store.inStock": "In Stock",
    "store.outOfStock": "Out of Stock",
    "store.quantity": "Quantity",
    "store.total": "Total",
    "store.subtotal": "Subtotal",
    "store.shipping": "Shipping",
    "store.tax": "Tax",
    "store.proceedToCheckout": "Proceed to Checkout",
    "store.continueShopping": "Continue Shopping",
    "store.emptyCart": "Your cart is empty",
    "store.removeFromCart": "Remove from Cart",
    "store.clearCart": "Clear Cart",

    // Calendar
    "calendar.title": "Ritual Calendar",
    "calendar.today": "Today",
    "calendar.month": "Month",
    "calendar.week": "Week",
    "calendar.day": "Day",
    "calendar.addEvent": "Add Event",
    "calendar.editEvent": "Edit Event",
    "calendar.deleteEvent": "Delete Event",
    "calendar.eventDetails": "Event Details",
    "calendar.startTime": "Start Time",
    "calendar.endTime": "End Time",
    "calendar.location": "Location",
    "calendar.description": "Description",
    "calendar.participants": "Participants",
    "calendar.reminder": "Reminder",
    "calendar.repeat": "Repeat",
    "calendar.noEvents": "No events scheduled",

    // Covens
    "covens.title": "Covens",
    "covens.myCovens": "My Covens",
    "covens.discover": "Discover Covens",
    "covens.createCoven": "Create Coven",
    "covens.joinCoven": "Join Coven",
    "covens.leaveCoven": "Leave Coven",
    "covens.members": "Members",
    "covens.posts": "Posts",
    "covens.events": "Events",
    "covens.settings": "Coven Settings",
    "covens.invite": "Invite Members",
    "covens.pending": "Pending Invitations",
    "covens.description": "Description",
    "covens.rules": "Rules",
    "covens.moderators": "Moderators",
    "covens.owner": "Owner",
    "covens.member": "Member",
    "covens.admin": "Admin",
    "covens.noCovens": "No covens found",
  },
  es: {
    // Navigation
    "nav.feed": "Diario del Diablo",
    "nav.reels": "Sinagoga de Pecadores",
    "nav.friends": "Aliados",
    "nav.covens": "Aquelarres",
    "nav.chat": "Chat Infernal",
    "nav.ouija": "Cámara Ouija",
    "nav.tarot": "Lectura de Tarot",
    "nav.rune": "Lanzamiento de Runas",
    "nav.solomon": "Cámara de Salomón",
    "nav.calendar": "Calendario Ritual",

    // Solomon's Chamber
    "solomon.title": "Cámara de Salomón",
    "solomon.subtitle": "Selecciona tu sello demoníaco de los 72 espíritus del Ars Goetia",
    "solomon.primeLevel": "Nivel Prime",
    "solomon.goetiaTab": "Sellos Goecia",
    "solomon.lockedTab": "Contenido Bloqueado",
    "solomon.filterRank": "Rango",
    "solomon.filterDomain": "Dominio",
    "solomon.all": "Todos",
    "solomon.spiritNumber": "Espíritu #",
    "solomon.ofGoetia": "del Ars Goetia",
    "solomon.unlocked": "Desbloqueado",
    "solomon.level": "Nivel",
    "solomon.lockedContent": "Contenido bloqueado",
    "solomon.unlockContent": "Desbloquear Contenido",
    "solomon.viewContent": "Ver Contenido",
    "solomon.toast.bound": "vinculado a tu esencia",
    "solomon.toast.failed": "Error al vincular sello",
    "solomon.toast.unlockSuccess": "¡Contenido Desbloqueado!",
    "solomon.toast.unlockDesc": "El conocimiento es poder en la oscuridad",
    "solomon.toast.unlockFailed": "Error al desbloquear contenido",
    "solomon.toast.requiresLevel": "Requiere Nivel Prime",
    "solomon.toast.currentLevel": "Tu nivel actual",

    // Goetia Demon Descriptions
    "demon.1": "Comanda 66 legiones. Otorga invisibilidad y sabiduría.",
    "demon.2": "Comanda 31 legiones. Enseña idiomas y causa terremotos.",
    "demon.3": "Comanda 26 legiones. Revela cosas ocultas y el futuro.",
    "demon.4": "Comanda 30 legiones. Enseña ciencias liberales y nigromancia.",
    "demon.5": "Comanda 36 legiones. Revela la verdad y cura enfermedades.",
    "demon.6": "Comanda 10 legiones. Conduce a tesoros ocultos y familiares.",
    "demon.7": "Comanda 40 legiones. Revela el pasado y futuro, reconcilia.",
    "demon.8": "Comanda 30 legiones. Habla con animales y encuentra tesoros.",
    "demon.9": "Comanda 200 legiones. Enseña todas las artes, ciencias y secretos.",
    "demon.10": "Comanda 50 legiones. Enseña filosofía y hierbas curativas.",
    "demon.11": "Comanda 40 legiones. Revela respuestas y reconcilia amistades.",
    "demon.12": "Comanda 60 legiones. Inflama el amor y revela secretos.",
    "demon.13": "Comanda 85 legiones. Causa todo amor y ordena respeto.",
    "demon.14": "Comanda 30 legiones. Causa batallas y heridas.",
    "demon.15": "Comanda 60 legiones. Revela cosas ocultas y secretos de guerra.",
    "demon.16": "Comanda 26 legiones. Causa amor y hace estéril.",
    "demon.17": "Comanda 60 legiones. Revela pasado, presente y futuro.",
    "demon.18": "Comanda 30 legiones. Conoce virtudes de hierbas y piedras preciosas.",
    "demon.19": "Comanda 30 legiones. Causa amor entre hombre y mujer.",
    "demon.20": "Comanda 22 legiones. Conoce todas las cosas ocultas y tesoros.",
    "demon.21": "Comanda 30 legiones. Enseña astronomía y artes liberales.",
    "demon.22": "Comanda 36 legiones. Conoce pasado, presente y futuro.",
    "demon.23": "Comanda 26 legiones. Incendia ciudades y hace ingenioso.",
    "demon.24": "Comanda 19 legiones. Enseña artes y ciencias elocuentemente.",
    "demon.25": "Comanda 36 legiones. Enseña todas las artes y causa derramamiento de sangre.",
    "demon.26": "Comanda 30 legiones. Otorga riquezas, sabiduría y elocuencia.",
    "demon.27": "Comanda 19 legiones. Enseña retórica e idiomas.",
    "demon.28": "Comanda 26 legiones. Convierte metales en oro y revela la verdad.",
    "demon.29": "Comanda 40 legiones. Responde preguntas sobre el pasado.",
    "demon.30": "Comanda 29 legiones. Enseña retórica y hace amado.",
    "demon.31": "Comanda 29 legiones. Enseña lógica y ética.",
    "demon.32": "Comanda 72 legiones. Enseña aritmética y hace invisible.",
    "demon.33": "Comanda 66 legiones. Hace insensible y causa amor.",
    "demon.34": "Comanda 26 legiones. Causa amor y levanta tormentas.",
    "demon.35": "Comanda 30 legiones. Responde con verdad y espera regresar.",
    "demon.36": "Comanda 26 legiones. Enseña astronomía y hierbas.",
    "demon.37": "Comanda 20 legiones. Enseña ciencias y poesía.",
    "demon.38": "Comanda 26 legiones. Construye torres y suministra armas.",
    "demon.39": "Comanda 40 legiones. Construye casas y destruye enemigos.",
    "demon.40": "Comanda 30 legiones. Roba tesoros y destruye ciudades.",
    "demon.41": "Comanda 30 legiones. Controla vientos y ahoga hombres.",
    "demon.42": "Comanda 29 legiones. Guía las aguas y causa muerte.",
    "demon.43": "Comanda 50 legiones. Construye castillos y causa heridas.",
    "demon.44": "Comanda 30 legiones. Roba y descubre cosas ocultas.",
    "demon.45": "Comanda 36 legiones. Revela brujas y construye torres.",
    "demon.46": "Comanda 6 legiones. Enseña astrología y geometría.",
    "demon.47": "Comanda 37 legiones. Procura amor y revela el pasado.",
    "demon.48": "Comanda 33 legiones. Transmuta metales y otorga sabiduría.",
    "demon.49": "Comanda 48 legiones. Enseña geometría y calienta aguas.",
    "demon.50": "Comanda 20 legiones. Enseña filosofía y adivinación.",
    "demon.51": "Comanda 40 legiones. Otorga invisibilidad e ingenio.",
    "demon.52": "Comanda 36 legiones. Enseña astronomía y artes liberales.",
    "demon.53": "Comanda 30 legiones. Da comprensión de animales.",
    "demon.54": "Comanda 30 legiones. Enseña filosofía y restringe almas.",
    "demon.55": "Comanda 20 legiones. Revela la verdad y protege.",
    "demon.56": "Comanda 26 legiones. Cuenta de tesoros y procura amor.",
    "demon.57": "Comanda 3 legiones. Transforma y enloquece.",
    "demon.58": "Comanda 36 legiones. Enseña astrología y artes liberales.",
    "demon.59": "Comanda 30 legiones. Enseña astrología y transforma.",
    "demon.60": "Comanda 36 legiones. Enseña oficios y filosofía.",
    "demon.61": "Comanda 33 legiones. Transmuta y hace ingenioso.",
    "demon.62": "Comanda 38 legiones. Revela serpientes y tesoros.",
    "demon.63": "Comanda 30 legiones. Siembra discordia y mata.",
    "demon.64": "Comanda 36 legiones. Revela el pasado y destruye enemigos.",
    "demon.65": "Comanda 30 legiones. Enseña geometría y astronomía.",
    "demon.66": "Comanda 20 legiones. Enseña gramática y revela tesoros.",
    "demon.67": "Comanda 29 legiones. Da instrumentos musicales.",
    "demon.68": "Comanda 80 legiones. Distribuye títulos y da familiares.",
    "demon.69": "Comanda 30 legiones. Conoce virtudes de aves y piedras.",
    "demon.70": "Comanda 26 legiones. Viaja rápidamente y revela ladrones.",
    "demon.71": "Comanda 36 legiones. Conoce pensamientos y los cambia.",
    "demon.72": "Comanda 36 legiones. Revela ladrones y castiga.",

    "nav.store": "Tienda Prime",
    "nav.profile": "Mi Castillo",
    "nav.settings": "Configuración",
    "nav.viewCastle": "Ver Castillo",
    "nav.premiumServices": "Servicios Premium",

    // Header
    "header.search": "Buscar en la oscuridad...",
    "header.notifications": "Notificaciones",
    "header.castle": "Mi Castillo",

    // Tarot Reading
    "tarot.title": "🔮 Cámara de Lectura de Tarot",
    "tarot.previousReadings": "Lecturas anteriores",
    "tarot.accessRequired": "El acceso a la Cámara de Tarot requiere una clave de lectura o token de invitación.",
    "tarot.enterToken": "Ingresa Tu Token",
    "tarot.tokenPlaceholder": "XXXX-XXXX-XXXX",
    "tarot.validateToken": "Validar Token",
    "tarot.purchaseKey": "O compra una clave de lectura en la tienda",
    "tarot.spreadType": "Tipo de Tirada",
    "tarot.spiritTone": "Tono del Espíritu",
    "tarot.beginReading": "Comenzar Lectura",
    "tarot.interpretation": "Interpretación",
    "tarot.exportTranscript": "Exportar Transcripción",
    "tarot.newReading": "Nueva Lectura",
    "tarot.drawingCards": "Sacando cartas del mazo cósmico...",
    "tarot.reversed": "Invertida",
    
    // Spread Types
    "tarot.spread.1card": "Una Carta - Visión Rápida",
    "tarot.spread.3card": "Tres Cartas - Pasado, Presente, Futuro",
    "tarot.spread.celtic": "Cruz Celta - Inmersión Profunda",
    
    // Spirit Tones
    "tarot.tone.poetic": "Poético - Místico y Metafórico",
    "tarot.tone.factual": "Factual - Directo y Práctico",
    "tarot.tone.chaotic": "Caótico - Impredecible y Salvaje",
    "tarot.tone.silent": "Silencioso - Pocas Palabras, Significado Profundo",

    // Rune Casting
    "rune.title": "⚔️ Cámara de Lanzamiento de Runas",
    "rune.previousCastings": "Lanzamientos anteriores",
    "rune.accessRequired": "El acceso a la Cámara de Runas requiere una clave de lanzamiento o token de invitación.",
    "rune.enterToken": "Ingresa Tu Token",
    "rune.tokenPlaceholder": "XXXX-XXXX-XXXX",
    "rune.validateToken": "Validar Token",
    "rune.purchaseKey": "O compra una clave de lanzamiento en la tienda",
    "rune.spreadType": "Tipo de Tirada",
    "rune.spiritTone": "Tono del Espíritu",
    "rune.beginCasting": "Comenzar Lanzamiento",
    "rune.interpretation": "Interpretación",
    "rune.exportTranscript": "Exportar Transcripción",
    "rune.newCasting": "Nuevo Lanzamiento",
    "rune.castingRunes": "Lanzando runas del conjunto antiguo...",
    "rune.reversed": "Invertida",
    "rune.spread.1rune": "Una Runa - Visión Rápida",
    "rune.spread.3rune": "Tres Runas - Pasado, Presente, Futuro",
    "rune.spread.9rune": "Cuadrícula de Nueve Runas - Mapa Espiritual Completo",
    "rune.tone.poetic": "Poético - Místico y Metafórico",
    "rune.tone.factual": "Factual - Directo y Práctico",
    "rune.tone.chaotic": "Caótico - Impredecible y Salvaje",
    "rune.tone.silent": "Silencioso - Pocas Palabras, Significado Profundo",
    "rune.error.invalidToken": "Token inválido o ya usado",
    "rune.error.startFailed": "Error al iniciar sesión de lanzamiento",
    "rune.error.castFailed": "Error al lanzar runas",
    "rune.error.interpretFailed": "Error al generar interpretación",
    "rune.success.accessGranted": "¡Acceso concedido! Tu token ha sido activado.",
    "rune.success.exported": "Transcripción exportada",

    // Ouija Chamber
    "ouija.title": "Cámara Ouija Infernal",
    "ouija.subtitle": "Crea una sala de sesión e invita hasta 5 amigos. Cada sesión permite 6 preguntas antes de que los espíritus se vayan.",
    "ouija.createRoom": "Crear Sala",
    "ouija.summonSpirit": "Invocar Espíritu",
    "ouija.tokenCode": "Código de Token",
    "ouija.adminOptional": "(Admin: Opcional)",
    "ouija.enterToken": "Ingresa tu código de token",
    "ouija.creating": "Creando...",
    "ouija.createSeance": "Crear Sala de Sesión",
    "ouija.purchaseToken": "Comprar Token (Demo)",
    "ouija.tokenInfo": "Los tokens son consumibles y te permiten organizar una sesión. Comparte el código de invitación con hasta 5 participantes.",
    "ouija.summonedSpirit": "Espíritu Invocado",
    "ouija.questionsRemaining": "Preguntas Restantes",
    "ouija.currentTurn": "Turno Actual",
    "ouija.you": "(Tú)",
    "ouija.copyInvite": "Copiar Invitación",
    "ouija.participants": "Participantes",
    "ouija.spiritSpeaks": "El espíritu habla a través del movimiento...",
    "ouija.watchPlanchette": "Observa cómo la plancheta deletrea la respuesta",
    "ouija.hoveringOver": "Sobre:",
    "ouija.askQuestion": "Pregúntale a los espíritus...",
    "ouija.askSpirit": "Preguntar al Espíritu",
    "ouija.spiritResponses": "Respuestas del Espíritu",
    "ouija.clearLog": "Limpiar Registro",
    "ouija.sessionEnded": "Sesión Finalizada",
    "ouija.spiritsDepart": "Los espíritus se han ido después de 6 preguntas.",
    "ouija.questionsAsked": "Preguntas Realizadas:",
    "ouija.exitRoom": "Salir de la Sala",
    "ouija.inviteCopied": "¡Enlace de Invitación Copiado!",
    "ouija.inviteDesc": "Comparte este enlace con hasta 5 participantes.",
    "ouija.tokenRequired": "Token Requerido",
    "ouija.tokenRequiredDesc": "Por favor ingresa tu código de token para crear una sala.",
    "ouija.invalidToken": "Token Inválido",
    "ouija.invalidTokenDesc": "Este token no existe o ya ha sido usado.",
    "ouija.roomCreated": "¡Sala Creada!",
    "ouija.shareInvite": "Comparte el código de invitación:",
    "ouija.error": "Error",
    "ouija.errorDesc": "Ocurrió un error inesperado.",
    "ouija.tokenPurchased": "¡Token Comprado!",
    "ouija.yourToken": "Tu código de token:",
    "ouija.spiritsReached": "No se pudo contactar a los espíritus.",
    "ouija.letterDetected": "Letra Detectada",
    "ouija.spiritHovers": "El espíritu se cierne sobre:",
    "ouija.spirits.the_whisperer": "El Susurrador",
    "ouija.spirits.the_archivist": "El Archivista",
    "ouija.spirits.the_trickster": "El Bromista",
    "ouija.spirits.the_watcher": "El Observador",
    "ouija.spirits.the_whisperer_desc": "Respuestas crípticas y poéticas",
    "ouija.spirits.the_archivist_desc": "Respuestas históricas y factuales",
    "ouija.spirits.the_trickster_desc": "Respuestas caóticas y engañosas",
    "ouija.spirits.the_watcher_desc": "Símbolos crípticos y silenciosos",

    // Common Actions
    "action.save": "Guardar",
    "action.cancel": "Cancelar",
    "action.delete": "Eliminar",
    "action.edit": "Editar",
    "action.create": "Crear",
    "action.update": "Actualizar",
    "action.close": "Cerrar",
    "action.submit": "Enviar",

    // Notifications
    "notification.success": "Éxito",
    "notification.error": "Error",
    "notification.warning": "Advertencia",
    "notification.info": "Información",

    // Auth
    "auth.login": "Iniciar Sesión",
    "auth.logout": "Cerrar Sesión",
    "auth.signup": "Registrarse",
    "auth.email": "Correo Electrónico",
    "auth.password": "Contraseña",

    // Profile
    "profile.edit": "Editar Perfil",
    "profile.username": "Nombre de Usuario",
    "profile.bio": "Biografía",
    "profile.location": "Ubicación",
    "profile.dateOfBirth": "Fecha de Nacimiento",
    "profile.zodiac": "Signo Zodiacal",
    "profile.background": "Antecedentes",
    "profile.careerFocus": "Enfoque Profesional",
    "profile.relationship": "Estado de Relación",

    // Video Upload
    "upload.title": "Sube Tu Contenido Infernal",
    "upload.uploadText": "¡Sube Tu Video!",
    "upload.clickOrDrag": "Haz clic para seleccionar o arrastra y suelta",
    "upload.maxSize": "Máximo 50MB",
    "upload.titleLabel": "Título",
    "upload.titlePlaceholder": "El Ritual de Medianoche...",
    "upload.categoryLabel": "Categoría de Video (7 Pecados Capitales)",
    "upload.categoryPlaceholder": "Selecciona una categoría...",
    "upload.descriptionLabel": "Descripción del Contenido",
    "upload.descriptionPlaceholder": "Pronuncia las palabras de poder...",
    "upload.tagsLabel": "Agrega Tus Hash Tags#",
    "upload.tagsPlaceholder": "Agregar etiqueta...",
    "upload.addButton": "Agregar",
    "upload.unleashButton": "Liberar Video",
    "upload.uploading": "Invocando...",
    "upload.disciples": "Discípulos de Video",
    "upload.legionUnlocked": "6 Legiones Desbloqueadas - videos de 5min habilitados",
    "upload.toLegion": "más para desbloquear 6 Legiones",
    "upload.maxSize60sec": "Máx 60 segundos (necesitas 6,000 discípulos para 3-5min)",
    "upload.maxSize5min": "Máx 5 minutos - 50MB",
    "upload.error.notVideo": "Por favor selecciona un archivo de video",
    "upload.error.tooLarge": "El video debe ser menor a 50MB",
    "upload.error.needLegions": "Necesitas 6,000 discípulos (6 Legiones) para subir videos de más de 60 segundos",
    "upload.error.max5min": "La duración máxima del video es 5 minutos (300 segundos)",

    // Reels
    "reels.loadingVideos": "Cargando videos...",
    "reels.noVideos": "No hay videos aún",
    "reels.ritualInterrupted": "Ritual Interrumpido",
    "reels.retry": "Reintentar",
    "reels.anonymous": "Anónimo",
    "reels.loadingMore": "Cargando más...",
    "reels.noMoreVideos": "No hay más videos",
    "reels.alreadyReacted": "Ya reaccionaste",

    // Search
    "search.title": "Búsqueda Avanzada - Diario del Diablo",
    "search.placeholder": "Buscar usuarios, posts, videos, aquelarres...",
    "search.search": "Buscar",
    "search.searching": "Buscando...",
    "search.filterBy": "Filtrar por",
    "search.all": "Todo",
    "search.username": "Nombre de Usuario",
    "search.location": "Ubicación",
    "search.users": "Usuarios",
    "search.posts": "Posts",
    "search.videos": "Videos",
    "search.covens": "Aquelarres",
    "search.noUsers": "No se encontraron usuarios",
    "search.noPosts": "No se encontraron posts",
    "search.noVideos": "No se encontraron videos",
    "search.noCovens": "No se encontraron aquelarres",

    // Occult Library
    "library.title": "📚 Biblioteca Oculta",
    "library.subtitle": "Grimorios Antiguos y Conocimiento Prohibido",
    "library.featured": "Tomos Destacados",
    "library.collection": "Colección Sagrada",
    "library.searchPlaceholder": "Buscar grimorios...",
    "library.allCategories": "Todas las Categorías",
    "library.sortBy": "Ordenar por",
    "library.newest": "Más Reciente",
    "library.oldest": "Más Antiguo",
    "library.popular": "Más Popular",
    "library.subscribeInfo": "Suscríbete para acceso ilimitado a este y todos los libros",
    "library.pricePerMonth": "$29.99/mes",
    "library.unlimitedReading": "Lectura Ilimitada",
    "library.subscribeButton": "Suscribirse para Acceso Ilimitado",
    "library.processing": "Procesando...",
    "library.read": "Leer Ahora",
    "library.download": "Descargar",
    "library.preview": "Vista Previa",
    "library.pages": "páginas",
    "library.author": "Autor",
    "library.published": "Publicado",
    "library.category": "Categoría",
    "library.description": "Descripción",
    "library.chapters": "Capítulos",
    "library.reviews": "Reseñas",
    "library.rating": "Calificación",
    "library.addToLibrary": "Agregar a Biblioteca",
    "library.inLibrary": "En Tu Biblioteca",
    "library.share": "Compartir",
    "library.report": "Reportar",
    "library.relatedBooks": "Libros Relacionados",
    "library.noBooks": "No se encontraron libros",
    "library.loadMore": "Cargar Más",
    "library.categories.rituals": "Rituales y Ceremonias",
    "library.categories.demons": "Demonología",
    "library.categories.spells": "Hechizos y Encantamientos",
    "library.categories.history": "Historia Oculta",
    "library.categories.philosophy": "Filosofía Oscura",
    "library.categories.divination": "Artes Adivinatorias",
    "library.categories.alchemy": "Alquimia",
    "library.categories.astral": "Proyección Astral",

    // Settings
    "settings.title": "Configuración",
    "settings.profile": "Configuración de Perfil",
    "settings.account": "Cuenta",
    "settings.privacy": "Privacidad",
    "settings.notifications": "Notificaciones",
    "settings.appearance": "Apariencia",
    "settings.language": "Idioma",
    "settings.theme": "Tema",
    "settings.darkMode": "Modo Oscuro",
    "settings.lightMode": "Modo Claro",
    "settings.autoMode": "Automático",
    "settings.emailNotifications": "Notificaciones por Email",
    "settings.pushNotifications": "Notificaciones Push",
    "settings.soundEffects": "Efectos de Sonido",
    "settings.changePassword": "Cambiar Contraseña",
    "settings.deleteAccount": "Eliminar Cuenta",
    "settings.privacyPolicy": "Política de Privacidad",
    "settings.termsOfService": "Términos de Servicio",
    "settings.logout": "Cerrar Sesión",
    "settings.saveChanges": "Guardar Cambios",
    "settings.discardChanges": "Descartar Cambios",

    // Chat
    "chat.title": "Chat Infernal",
    "chat.conversations": "Conversaciones",
    "chat.newMessage": "Nuevo Mensaje",
    "chat.searchMessages": "Buscar mensajes...",
    "chat.typePlaceholder": "Escribe un mensaje...",
    "chat.send": "Enviar",
    "chat.attach": "Adjuntar",
    "chat.emoji": "Emoji",
    "chat.voiceCall": "Llamada de Voz",
    "chat.videoCall": "Videollamada",
    "chat.moreOptions": "Más Opciones",
    "chat.online": "En Línea",
    "chat.offline": "Desconectado",
    "chat.typing": "escribiendo...",
    "chat.seen": "Visto",
    "chat.delivered": "Entregado",
    "chat.sent": "Enviado",
    "chat.failed": "Fallido",
    "chat.deleteMessage": "Eliminar Mensaje",
    "chat.editMessage": "Editar Mensaje",
    "chat.replyMessage": "Responder",
    "chat.forwardMessage": "Reenviar",
    "chat.copyMessage": "Copiar",
    "chat.noConversations": "No hay conversaciones aún",
    "chat.startConversation": "Iniciar una conversación",

    // Feed/Posts
    "feed.title": "Diario del Diablo",
    "feed.whatsOnMind": "¿Qué hay en tu mente oscura?",
    "feed.createPost": "Crear Post",
    "feed.shareThoughts": "Comparte tus pensamientos...",
    "feed.addPhoto": "Agregar Foto",
    "feed.addVideo": "Agregar Video",
    "feed.addLocation": "Agregar Ubicación",
    "feed.post": "Publicar",
    "feed.posting": "Publicando...",
    "feed.like": "Me gusta",
    "feed.comment": "Comentar",
    "feed.share": "Compartir",
    "feed.comments": "Comentarios",
    "feed.writeComment": "Escribe un comentario...",
    "feed.viewAllComments": "Ver todos los comentarios",
    "feed.hideComments": "Ocultar comentarios",
    "feed.edited": "Editado",
    "feed.deletePost": "Eliminar Post",
    "feed.editPost": "Editar Post",
    "feed.reportPost": "Reportar Post",
    "feed.savePost": "Guardar Post",
    "feed.unsavePost": "Desguardar Post",
    "feed.noPostsYet": "No hay posts aún",
    "feed.loadingPosts": "Cargando posts...",

    // Store
    "store.title": "Tienda Prime",
    "store.featuredItems": "Artículos Destacados",
    "store.categories": "Categorías",
    "store.cart": "Carrito",
    "store.checkout": "Pagar",
    "store.addToCart": "Agregar al Carrito",
    "store.buyNow": "Comprar Ahora",
    "store.price": "Precio",
    "store.inStock": "En Stock",
    "store.outOfStock": "Agotado",
    "store.quantity": "Cantidad",
    "store.total": "Total",
    "store.subtotal": "Subtotal",
    "store.shipping": "Envío",
    "store.tax": "Impuesto",
    "store.proceedToCheckout": "Proceder al Pago",
    "store.continueShopping": "Continuar Comprando",
    "store.emptyCart": "Tu carrito está vacío",
    "store.removeFromCart": "Quitar del Carrito",
    "store.clearCart": "Vaciar Carrito",

    // Calendar
    "calendar.title": "Calendario Ritual",
    "calendar.today": "Hoy",
    "calendar.month": "Mes",
    "calendar.week": "Semana",
    "calendar.day": "Día",
    "calendar.addEvent": "Agregar Evento",
    "calendar.editEvent": "Editar Evento",
    "calendar.deleteEvent": "Eliminar Evento",
    "calendar.eventDetails": "Detalles del Evento",
    "calendar.startTime": "Hora de Inicio",
    "calendar.endTime": "Hora de Fin",
    "calendar.location": "Ubicación",
    "calendar.description": "Descripción",
    "calendar.participants": "Participantes",
    "calendar.reminder": "Recordatorio",
    "calendar.repeat": "Repetir",
    "calendar.noEvents": "No hay eventos programados",

    // Covens
    "covens.title": "Aquelarres",
    "covens.myCovens": "Mis Aquelarres",
    "covens.discover": "Descubrir Aquelarres",
    "covens.createCoven": "Crear Aquelarre",
    "covens.joinCoven": "Unirse al Aquelarre",
    "covens.leaveCoven": "Abandonar Aquelarre",
    "covens.members": "Miembros",
    "covens.posts": "Posts",
    "covens.events": "Eventos",
    "covens.settings": "Configuración del Aquelarre",
    "covens.invite": "Invitar Miembros",
    "covens.pending": "Invitaciones Pendientes",
    "covens.description": "Descripción",
    "covens.rules": "Reglas",
    "covens.moderators": "Moderadores",
    "covens.owner": "Propietario",
    "covens.member": "Miembro",
    "covens.admin": "Administrador",
    "covens.noCovens": "No se encontraron aquelarres",
  },
};
